### ISSUE TITLE
how to get access / add functionality (ideally python)

### ISSUE THREAD

**Issue by pieper** [KitwareMedical/SlicerOpenVR#15]
First: excellent work 👍 

Second: I'm running a Slicer binary provided by Mark at Queens and I want to experiment with controls and widgets but it looks like nothing is exposed in python right now - is that true?

I realize I could compile from source and work in C++ but I'd prefer to write scripted modules.

**Comment by jcfr** [comment]
Hi Steve,

Thanks for the note.

It should be possible to easily give access to the renderer from Python. Is
what you mean ?

Jc

**Comment by pieper** [comment]
Hi @jcfr - I was thinking it would be great to query the controller locations, get vtk events one button presses, that sort of thing.  In Slicer we may want to mirror those values in MRML nodes but for initial experimentation we could make a lot of progress with some simple accessor methods.

For example at this point the camera controls are workable, but pretty simple.  And is there any connection yet with the vtk widgets?  These would be good things to try at project week.

**Comment by mattjolley** [comment]
We would benefit from this as well (again via the binary from Mark/the PERK group)

**Comment by jcfr** [comment]
@pieper :  Thanks to @cpinter , you can now get a reference to [qMRMLVRView](https://github.com/KitwareMedical/SlicerOpenVR/blob/6308d6ad664044ea501126a3594155de62677535/VR/Widgets/qMRMLVRView.h) using [vrWidget()](https://github.com/KitwareMedical/SlicerOpenVR/blob/6308d6ad664044ea501126a3594155de62677535/VR/qSlicerVRModuleWidget.h#L41) functions.

For example:

```
>>> slicer.modules.vr.widgetRepresentation().initializeVR()
>>> slicer.modules.vr.widgetRepresentation().vrWidget()
qMRMLVRView(0x623f7a0, name="VRWidget") 
```

Note that in the near future:
* name of function `vrWidget` may be changed into `vrView` shortly. 
* module and associated objects may be renamed to `VirtualReality`

**Comment by cpinter** [comment]
> name of function vrWidget may be changed into vrView shortly

Absolutely. I think I wanted to keep [this](https://github.com/KitwareMedical/SlicerOpenVR/blob/16dcd1196272353e9856ec82568fde07ddac21a0/VR/qSlicerVRModuleWidget.cxx#L98-L103) naming convention

**Comment by pieper** [comment]
👍

**Comment by cpinter** [comment]
Few snippets that work for me and may be helpful:

```
    # Get VR module widget
    vrModuleWidget = slicer.modules.virtualreality.widgetRepresentation()
    if vrModuleWidget is None or vrModuleWidget.vrWidget() is None:
      return

    # Get VR camera
    rendererCollection = vrModuleWidget.vrWidget().renderWindow().GetRenderers()
    if rendererCollection.GetNumberOfItems() < 1:
      logging.error('Unable to access VR renderers')
    self.vrCamera = rendererCollection.GetItemAsObject(0).GetActiveCamera()
```

```
    # Determine if VR has been initialized
    vrInitialized = (vrModuleWidget is not None and vrModuleWidget.vrWidget() is not None and vrModuleWidget.vrWidget().mrmlVRViewNode() is not None)
```

**Comment by pieper** [comment]
That's helpful @cpinter !

Is it also possible to show and example of adding observers to the controller buttons and getting out the controller transform?

**Comment by cpinter** [comment]
It would be very useful indeed and I want to have these too. I am still working on more low-level issues, such as that VTK does not handle the Oculus controller (I use an Oculus nowadays), or multi-volume rendering in Slicer.
In the meantime I can give pointers where in the VTKRenderingOpenVR code the interactions are handled that need to be exposed.

**Comment by pieper** [comment]
Thanks - No rush - just curious!

**Comment by jcfr** [comment]
Thanks @cpinter , added a "Python snippet" section to the README file. See https://github.com/KitwareMedical/SlicerVirtualReality/blob/master/README.md#useful-python-snippets

**Comment by cpinter** [comment]
Great! I was thinking about adding this to the Slicer script repo, but it doesn't belong there. This way is perfect, thanks!
