### ISSUE TITLE
Exclude VR view from main layout management

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerOpenVR#18]
Node reference parentLayoutNodeID in view nodes
* None by default, meaning main layout. Set to node (e.g. itself) to indicate it’s standalone and should not be managed
* Abstract layout node class
  * Current layout node and the new VR layout node will be its child classes
  * VR “layout” may contain HUD-like objects such as slice views or charts that are positioned and kept stationary in the VR view by the layout

**Comment by cpinter** [comment]
@jcfr Please assign this to me (or give me right to do it). Thanks!

**Comment by jcfr** [comment]
> Please assign this to me (or give me right to do it). Thanks!

You know have push access to the repo.

**Comment by cpinter** [comment]
Perfect, thank you!

**Comment by cpinter** [comment]
Integrated in https://github.com/Slicer/Slicer/commit/2e316564d343be446c7f8251ec86430661566e17

I just opened a PR to SlicerOpenVR: https://github.com/KitwareMedical/SlicerOpenVR/pull/20

After this (and after solving the extension packaging issues) SlicerOpenVR will work with Slicer master as is.

**Comment by jcfr** [comment]
Closing. This was fixed in https://github.com/KitwareMedical/SlicerOpenVR/commit/6308d6ad664044ea501126a3594155de62677535
